echo "# Python_Project" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/CommunistPotato1231/Python_Project.git
git push -u origin master


